# =====================================================================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================


spring:
  application:
    name: SITMUN
  profiles:
    active: oracle
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    rest:
      default-page-size: 100000
      max-page-size: 100000
  jackson:
    serialization:
      fail_on_empty_beans: false
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      # modify fetch size as necessary
      hibernate.jdbc.fetch_size: 150
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      # Disable Hibernate validation to avoid double validation
      javax.persistence.validation.mode: none
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: sample-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: sample-scheduling-
      pool:
        size: 2

server:
  servlet:
    session:
      cookie:
        http-only: true

# ===================================================================
# SITMUN specific properties
# ===================================================================

sitmun:
  module: SITMUN Core
  version: 3.0-SNAPSHOT
  proxy:
    config-response-validity-in-seconds: 3600



# ===================================================================
# Image Scaling
# ===================================================================

imagescaling:
  supportedFormats:
    - png
    - jpg
    - jpeg
  defaultWidth: 125
  defaultHeight: 125
  sizes:
    - type: menu
      width: 50
      height: 50
    - type: list
      width: 25
      height: 25
