--liquibase formatted sql
--changeset sitmun:3 context:dev

INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (10, 'Name of Role 10', 'Description of Role 10');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (14, 'Name of Role 14', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (17, 'Name of Role 17', 'Description of Role 17');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (18, 'Name of Role 18', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (19, 'Name of Role 19', 'Description of Role 19');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (21, 'Name of Role 21', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (22, 'Name of Role 22', 'Description of Role 22');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (23, 'Name of Role 23', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (26, 'Name of Role 26', 'Description of Role 26');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (27, 'Name of Role 27', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (28, 'Name of Role 28', 'Description of Role 28');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (29, 'Name of Role 29', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (30, 'Name of Role 30', 'Description of Role 30');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (31, 'Name of Role 31', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (33, 'Name of Role 33', 'Description of Role 33');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (34, 'Name of Role 34', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (49, 'Name of Role 49', 'Description of Role 49');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (54, 'Name of Role 54', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (67, 'Name of Role 67', 'Description of Role 67');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (72, 'Name of Role 72', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (74, 'Name of Role 74', 'Description of Role 74');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (75, 'Name of Role 75', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (78, 'Name of Role 78', 'Description of Role 78');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (80, 'Name of Role 80', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (81, 'Name of Role 81', 'Description of Role 81');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (82, 'Name of Role 82', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (83, 'Name of Role 83', 'Description of Role 83');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (84, 'Name of Role 84', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (85, 'Name of Role 85', 'Description of Role 85');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (86, 'Name of Role 86', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (90, 'Name of Role 90', 'Description of Role 90');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (91, 'Name of Role 91', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (92, 'Name of Role 92', 'Description of Role 92');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (93, 'Name of Role 93', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (94, 'Name of Role 94', 'Description of Role 94');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (98, 'Name of Role 98', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (99, 'Name of Role 99', 'Description of Role 99');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (100, 'Name of Role 100', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (101, 'Name of Role 101', 'Description of Role 101');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (102, 'Name of Role 102', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (107, 'Name of Role 107', 'Description of Role 107');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (108, 'Name of Role 108', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (109, 'Name of Role 109', 'Description of Role 109');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (110, 'Name of Role 110', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (111, 'Name of Role 111', 'Description of Role 111');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (112, 'Name of Role 112', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (113, 'Name of Role 113', 'Description of Role 113');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (114, 'Name of Role 114', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (115, 'Name of Role 115', 'Description of Role 115');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (116, 'Name of Role 116', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (118, 'Name of Role 118', 'Description of Role 118');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (119, 'Name of Role 119', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (120, 'Name of Role 120', 'Description of Role 120');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (121, 'Name of Role 121', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (122, 'Name of Role 122', 'Description of Role 122');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (123, 'Name of Role 123', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (125, 'Name of Role 125', 'Description of Role 125');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (127, 'Name of Role 127', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (128, 'Name of Role 128', 'Description of Role 128');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (129, 'Name of Role 129', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (130, 'Name of Role 130', 'Description of Role 130');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (131, 'Name of Role 131', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (133, 'Name of Role 133', 'Description of Role 133');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (135, 'Name of Role 135', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (136, 'Name of Role 136', 'Description of Role 136');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (137, 'Name of Role 137', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (138, 'Name of Role 138', 'Description of Role 138');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (139, 'Name of Role 139', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (140, 'Name of Role 140', 'Description of Role 140');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (141, 'Name of Role 141', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (143, 'Name of Role 143', 'Description of Role 143');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (144, 'Name of Role 144', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (145, 'Name of Role 145', 'Description of Role 145');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (146, 'Name of Role 146', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (147, 'Name of Role 147', 'Description of Role 147');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (148, 'Name of Role 148', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (149, 'Name of Role 149', 'Description of Role 149');
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (150, 'Name of Role 150', null);
INSERT INTO STM_ROLE(ROL_ID, ROL_NAME, ROL_NOTE)
VALUES (151, 'Name of Role 151', 'Description of Role 151');

INSERT INTO STM_SEQUENCE(SEQ_NAME, SEQ_COUNT)
VALUES ('ROL_ID', 151);
