package org.sitmun.infrastructure.web.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.HashMap;
import java.util.Map;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * RFC 9457 Problem Details for HTTP APIs.
 *
 * <p>This class represents a standard error response format as defined in RFC 9457. It provides a
 * machine-readable format for specifying errors in HTTP API responses.
 *
 * <p>Standard fields: 
 * <ul>
 * <li>type: A URI reference that identifies the problem type</li>
 * <li>status: The HTTP status code</li>
 * <li>title: A short, human-readable summary of the problem type</li>
 * <li>detail: A human-readable explanation specific to this occurrence</li>
 * <li>instance: A URI reference that identifies the specific occurrence of the problem</li>
 * </ul>
 * <p>Extension members can be added via the properties map.
 *
 * @see <a href="https://www.rfc-editor.org/rfc/rfc9457.html">RFC 9457</a>
 */
@Builder
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetail {

  /**
   * A URI reference (RFC3986) that identifies the problem type. When dereferenced, it SHOULD
   * provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).
   *
   * <p>When this member is not present, its value is assumed to be "about:blank".
   */
  private String type;

  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  private Integer status;

  /**
   * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to
   * occurrence of the problem, except for purposes of localization.
   */
  private String title;

  /**
   * A human-readable explanation specific to this occurrence of the problem. It MAY change from
   * occurrence to occurrence of the problem.
   */
  private String detail;

  /**
   * A URI reference that identifies the specific occurrence of the problem. It may or may not
   * yield further information if dereferenced.
   */
  private String instance;

  /**
   * Extension members - additional properties that provide more context about the error. This
   * allows for problem type-specific extensions.
   */
  @Builder.Default private Map<String, Object> properties = new HashMap<>();

  /**
   * Add an extension property to the problem detail.
   *
   * @param key the property name
   * @param value the property value
   * @return this ProblemDetail instance for method chaining
   */
  public ProblemDetail addProperty(String key, Object value) {
    this.properties.put(key, value);
    return this;
  }
}

