--liquibase formatted sql
--changeset sitmun:7 runOnChange:true

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ABC_ID), 0) + 1 FROM STM_APP_BCKG) WHERE SEQ_NAME = 'ABC_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'ABC_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(ABC_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_APP_BCKG) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'ABC_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ATR_ID), 0) + 1 FROM STM_APP_TREE) WHERE SEQ_NAME = 'ATR_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'ATR_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(ATR_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_APP_TREE) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'ATR_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(AGI_ID), 0) + 1 FROM STM_AVAIL_GI) WHERE SEQ_NAME = 'AGI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'AGI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(AGI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_AVAIL_GI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'AGI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(APP_ID), 0) + 1 FROM STM_APP) WHERE SEQ_NAME = 'APP_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'APP_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(APP_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_APP) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'APP_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ATE_ID), 0) + 1 FROM STM_APP_TER) WHERE SEQ_NAME = 'ATE_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'ATE_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(ATE_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_APP_TER) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'ATE_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ATS_ID), 0) + 1 FROM STM_AVAIL_TSK) WHERE SEQ_NAME = 'ATS_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'ATS_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(ATS_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_AVAIL_TSK) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'ATS_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(BAC_ID), 0) + 1 FROM STM_BACKGRD) WHERE SEQ_NAME = 'BAC_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'BAC_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(BAC_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_BACKGRD) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'BAC_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(CNF_ID), 0) + 1 FROM STM_CONF) WHERE SEQ_NAME = 'CNF_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'CNF_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(CNF_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_CONF) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'CNF_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(COD_ID), 0) + 1 FROM STM_CODELIST) WHERE SEQ_NAME = 'COD_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'COD_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(COD_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_CODELIST) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'COD_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(COM_ID), 0) + 1 FROM STM_COMMENT) WHERE SEQ_NAME = 'COM_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'COM_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(COM_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_COMMENT) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'COM_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(CON_ID), 0) + 1 FROM STM_CONNECT) WHERE SEQ_NAME = 'CON_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'CON_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(CON_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_CONNECT) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'CON_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(FGI_ID), 0) + 1 FROM STM_FIL_GI) WHERE SEQ_NAME = 'FGI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'FGI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(FGI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_FIL_GI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'FGI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GEO_ID), 0) + 1 FROM STM_GEOINFO) WHERE SEQ_NAME = 'GEO_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'GEO_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(GEO_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_GEOINFO) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'GEO_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GGI_ID), 0) + 1 FROM STM_GRP_GI) WHERE SEQ_NAME = 'GGI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'GGI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(GGI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_GRP_GI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'GGI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GTS_ID), 0) + 1 FROM STM_GRP_TSK) WHERE SEQ_NAME = 'GTS_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'GTS_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(GTS_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_GRP_TSK) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'GTS_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GTT_ID), 0) + 1 FROM STM_GTER_TYP) WHERE SEQ_NAME = 'GTT_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'GTT_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(GTT_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_GTER_TYP) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'GTT_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LAN_ID), 0) + 1 FROM STM_LANGUAGE) WHERE SEQ_NAME = 'LAN_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'LAN_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(LAN_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_LANGUAGE) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'LAN_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LOG_ID), 0) + 1 FROM STM_LOG) WHERE SEQ_NAME = 'LOG_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'LOG_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(LOG_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_LOG) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'LOG_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PAP_ID), 0) + 1 FROM STM_PAR_APP) WHERE SEQ_NAME = 'PAP_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'PAP_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(PAP_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_PAR_APP) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'PAP_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PGI_ID), 0) + 1 FROM STM_PAR_GI) WHERE SEQ_NAME = 'PGI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'PGI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(PGI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_PAR_GI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'PGI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(POS_ID), 0) + 1 FROM STM_POST) WHERE SEQ_NAME = 'POS_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'POS_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(POS_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_POST) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'POS_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PSE_ID), 0) + 1 FROM STM_PAR_SER) WHERE SEQ_NAME = 'PSE_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'PSE_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(PSE_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_PAR_SER) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'PSE_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PSG_ID), 0) + 1 FROM STM_PAR_SGI) WHERE SEQ_NAME = 'PSG_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'PSG_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(PSG_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_PAR_SGI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'PSG_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ROL_ID), 0) + 1 FROM STM_ROLE) WHERE SEQ_NAME = 'ROL_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'ROL_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(ROL_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_ROLE) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'ROL_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(SER_ID), 0) + 1 FROM STM_SERVICE) WHERE SEQ_NAME = 'SER_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'SER_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(SER_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_SERVICE) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'SER_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(SGI_ID), 0) + 1 FROM STM_STY_GI) WHERE SEQ_NAME = 'SGI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'SGI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(SGI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_STY_GI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'SGI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TAR_ID), 0) + 1 FROM STM_TASKREL) WHERE SEQ_NAME = 'TAR_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TAR_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TAR_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TASKREL) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TAR_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TAS_ID), 0) + 1 FROM STM_TASK) WHERE SEQ_NAME = 'TAS_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TAS_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TAS_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TASK) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TAS_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TER_ID), 0) + 1 FROM STM_TERRITORY) WHERE SEQ_NAME = 'TER_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TER_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TER_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TERRITORY) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TER_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TET_ID), 0) + 1 FROM STM_TER_TYP) WHERE SEQ_NAME = 'TET_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TET_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TET_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TER_TYP) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TET_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TNO_ID), 0) + 1 FROM STM_TREE_NOD) WHERE SEQ_NAME = 'TNO_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TNO_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TNO_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TREE_NOD) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TNO_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TRA_ID), 0) + 1 FROM STM_TRANSLATION) WHERE SEQ_NAME = 'TRA_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TRA_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TRA_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TRANSLATION) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TRA_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TRE_ID), 0) + 1 FROM STM_TREE) WHERE SEQ_NAME = 'TRE_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TRE_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TRE_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TREE) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TRE_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TUI_ID), 0) + 1 FROM STM_TSK_UI) WHERE SEQ_NAME = 'TUI_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TUI_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TUI_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TSK_UI) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TUI_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TTY_ID), 0) + 1 FROM STM_TSK_TYP) WHERE SEQ_NAME = 'TTY_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'TTY_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(TTY_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TSK_TYP) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'TTY_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(UCO_ID), 0) + 1 FROM STM_USR_CONF) WHERE SEQ_NAME = 'UCO_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'UCO_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(UCO_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_USR_CONF) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'UCO_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(USE_ID), 0) + 1 FROM STM_USER) WHERE SEQ_NAME = 'USE_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'USE_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(USE_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_USER) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'USE_ID');

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(USER_TOKEN_ID), 0) + 1 FROM STM_TOKEN_USER) WHERE SEQ_NAME = 'USER_TOKEN_ID';
INSERT INTO STM_SEQUENCE (SEQ_NAME, SEQ_COUNT) SELECT 'USER_TOKEN_ID', NEXT_SEQUENCE_VALUE FROM (SELECT COALESCE(MAX(USER_TOKEN_ID), 0) + 1 AS NEXT_SEQUENCE_VALUE FROM STM_TOKEN_USER) SEQUENCE_VALUE WHERE NOT EXISTS (SELECT 1 FROM STM_SEQUENCE WHERE SEQ_NAME = 'USER_TOKEN_ID');
