name: CI

"on":
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: dev
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
      - uses: actions/checkout@v5
        with:
          repository: sitmun/sitmun-shared
          ref: "${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}"
          path: sitmun-shared
      - run: chmod +x gradlew && ./gradlew publishToMavenLocal
        working-directory: sitmun-shared
      - run: chmod +x gradlew
      - run: ./gradlew build
